AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-backend

  Sample SAM Template for sam-backend
  
Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        Region: 'us-east-1'

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: app.lambdaHandler
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            Path: /hello
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts
  createUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/users/
      Handler: createUser.createUser
      Events:
        createUser:
          Type: HttpApi
          Properties:
            Path: /api/v1/users
            Method: post
  getUserById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/users/
      Handler: getUserById.getUserById
      Events:
        getUserById:
          Type: HttpApi
          Properties:
            Path: /api/v1/users/{id}
            Method: get
  
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - createUser.ts
        - getUserById.ts