AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-backend

  Sample SAM Template for sam-backend
  
Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        Region: 'us-east-1'

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            Path: /hello
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts
  createUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/users/
      Handler: createUser.createUser
      Events:
        createUser:
          Type: HttpApi
          Properties:
            Path: /api/v1/users
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - createUser.ts
  updateUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/users/
      Handler: updateUser.updateUser
      Events:
        updateUser:
          Type: HttpApi
          Properties:
            Path: /api/v1/users/{id}
            Method: put
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - updateUser.ts
  getUserById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/users/
      Handler: getUserById.getUserById
      Events:
        getUserById:
          Type: HttpApi
          Properties:
            Path: /api/v1/users/{id}
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - getUserById.ts
  deleteUserById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/users/
      Handler: deleteUserById.deleteUserById
      Events:
        deleteUserById:
          Type: HttpApi
          Properties:
            Path: /api/v1/users/{id}
            Method: delete
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - getUserById.ts
  createProduct:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/products/
      Handler: createProduct.createProduct
      Events:
        createProduct:
          Type: HttpApi
          Properties:
            Path: /api/v1/products
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - createProduct.ts
  getProducts:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/products/
      Handler: getProducts.getProducts
      Events:
        createProduct:
          Type: HttpApi
          Properties:
            Path: /api/v1/products
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - getProducts.ts
  getProductById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/products/
      Handler: getProductById.getProductById
      Events:
        getProductById:
          Type: HttpApi
          Properties:
            Path: /api/v1/products/{id}
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - getProductById.ts
  updateProduct:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/products/
      Handler: updateProduct.updateProduct
      Events:
        updateProduct:
          Type: HttpApi
          Properties:
            Path: /api/v1/products/{id}
            Method: put
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - updateProduct.ts
  deleteProductById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/products/
      Handler: deleteProductById.deleteProductById
      Events:
        deleteProductById:
          Type: HttpApi
          Properties:
            Path: /api/v1/products/{id}
            Method: delete
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - deleteProductById.ts
  createReview:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/reviews/
      Handler: createReview.createReview
      Events:
        createReview:
          Type: HttpApi
          Properties:
            Path: /api/v1/reviews
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - createReview.ts
  updateReview:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/reviews/
      Handler: updateReview.updateReview
      Events:
        updateReview:
          Type: HttpApi
          Properties:
            Path: /api/v1/reviews/{id}
            Method: put
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - updateReview.ts
  getReviews:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/reviews/
      Handler: getReviews.getReviews
      Events:
        getReviews:
          Type: HttpApi
          Properties:
            Path: /api/v1/products/{productId}/reviews
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - getReviews.ts
  getReviewById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/reviews/
      Handler: getReviewById.getReviewById
      Events:
        getReviewById:
          Type: HttpApi
          Properties:
            Path: /api/v1/products/{productId}/reviews/{reviewId}
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - getReviewById.ts