AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-backend

  Sample SAM Template for sam-backend
  
Globals:
  Function:
    Timeout: 3
    Runtime: nodejs18.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        AccessId: '12345'
        SecretKey: 'password'

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: app.lambdaHandler
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            Path: /hello
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts
  createUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/users/
      Handler: createUser.createUser
      Events:
        createUser:
          Type: HttpApi
          Properties:
            Path: /api/v1/users
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - createUser.ts